/**
 * @file driverTripStyles.ts
 * @description Trip cockpit card, speedometer gauge, duration timer, and broadcast button styles.
 */

import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({  cockpitCard: {
    backgroundColor: '#080D1A',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#1A2540',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 18,
    elevation: 10,
  },
  cockpitTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 14,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderColor: '#1A2540',
  },
  liveTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: 'rgba(239,68,68,0.12)',
    paddingHorizontal: 13,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.28)',
  },
  pulsingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#EF4444',
  },
  liveTagText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#F87171',
    letterSpacing: 1,
  },
  timerText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#F1F5F9',
    fontVariant: ['tabular-nums'],
    letterSpacing: 1,
  },
  speedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 18,
  },
  speedBox: {
    alignItems: 'center',
    backgroundColor: '#0D1526',
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: '#162240',
    minWidth: 92,
  },
  speedNum: {
    fontSize: 50,
    fontWeight: '900',
    color: '#38BDF8',
    lineHeight: 54,
    letterSpacing: -2,
  },
  speedUnit: {
    fontSize: 10,
    fontWeight: '800',
    color: '#334155',
    letterSpacing: 2,
  },
  routeCol: { flex: 1, gap: 1 },
  routeLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: '#334155',
    letterSpacing: 1.2,
    marginTop: 6,
  },
  routeVal: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  routeDest: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
    lineHeight: 18,
  },
  sosBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    backgroundColor: '#C41E1E',
    borderRadius: 14,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.35)',
    shadowColor: '#DC2626',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  sosBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },

  // ── SAFETY CARD ─────────────────────────────────────────,
  gpsPulsePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  gpsPulseDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#16A34A',
  },
  gpsPulseText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#16A34A',
  },
  startBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#1D4ED8',
    borderRadius: 22,
    paddingVertical: 18,
    paddingHorizontal: 20,
    shadowColor: '#1D4ED8',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.42,
    shadowRadius: 14,
    elevation: 8,
  },
  startBtnIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  startBtnText: { flex: 1 },
  startBtnLabel: { fontSize: 16, fontWeight: '800', color: '#FFFFFF', letterSpacing: -0.2 },
  startBtnSub: { fontSize: 11, color: 'rgba(255,255,255,0.65)', fontWeight: '500', marginTop: 2 },
  stopBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#DC2626',
    borderRadius: 22,
    paddingVertical: 18,
    shadowColor: '#DC2626',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.42,
    shadowRadius: 14,
    elevation: 8,
  },
  stopBtnText: { fontSize: 15, fontWeight: '800', color: '#FFFFFF', letterSpacing: 0.2 }
});
