/**
 * @file driverSafetyStyles.ts
 * @description SafeTrip camera preview, WebRTC streaming banner, and permission prompt styles.
 */

import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({  safetyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E0EAF8',
    shadowColor: '#1E40AF',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  safetyCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  safetyTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  shieldPill: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: '#ECFDF5',
    borderWidth: 1.5,
    borderColor: '#A7F3D0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  safetyTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
  },
  safetySub: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '500',
    marginTop: 1,
  },
  sensorRow: {
    flexDirection: 'row',
    gap: 6,
  },
  sensorPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
  },
  sensorOn: { backgroundColor: '#F0FDF4', borderColor: '#86EFAC' },
  sensorOff: { backgroundColor: '#F8FAFC', borderColor: '#CBD5E1' },
  sensorDot: { width: 5, height: 5, borderRadius: 3 },
  sensorText: { fontSize: 10, fontWeight: '800', letterSpacing: 0.3 },

  // ── PERMISSION PROMPT ────────────────────────────────────,
  permPrompt: {
    backgroundColor: '#F0F7FF',
    borderWidth: 1.5,
    borderColor: '#BFDBFE',
    borderRadius: 18,
    padding: 22,
    alignItems: 'center',
    marginBottom: 6,
  },
  permIconRing: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#DBEAFE',
    borderWidth: 2,
    borderColor: '#93C5FD',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  permTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1E40AF',
    marginBottom: 8,
    textAlign: 'center',
  },
  permDesc: {
    fontSize: 13,
    color: '#3B82F6',
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 18,
  },
  grantBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#2563EB',
    paddingHorizontal: 22,
    paddingVertical: 13,
    borderRadius: 14,
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
  },
  grantBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },

  // ── CAMERA VIEWFINDER ────────────────────────────────────,
  camWrapper: { gap: 0 },
  camFrame: {
    height: 250,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#000',
    position: 'relative',
  },
  camView: { flex: 1 },
  camTopHUD: {
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  recBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.5)',
  },
  recDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#EF4444' },
  recDotSmall: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#EF4444' },
  recText: { fontSize: 10, fontWeight: '800', color: '#FFFFFF', letterSpacing: 0.6 },
  flipBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  // Viewfinder corner brackets,
  corner: { position: 'absolute', width: 20, height: 20, borderColor: 'rgba(255,255,255,0.6)' },
  cTL: { top: 9, left: 9, borderTopWidth: 2, borderLeftWidth: 2, borderTopLeftRadius: 4 },
  cTR: { top: 9, right: 9, borderTopWidth: 2, borderRightWidth: 2, borderTopRightRadius: 4 },
  cBL: { bottom: 44, left: 9, borderBottomWidth: 2, borderLeftWidth: 2, borderBottomLeftRadius: 4 },
  cBR: { bottom: 44, right: 9, borderBottomWidth: 2, borderRightWidth: 2, borderBottomRightRadius: 4 },
  camBottomHUD: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(0,0,0,0.65)',
    paddingVertical: 9,
    paddingHorizontal: 13,
  },
  audioText: { fontSize: 11, fontWeight: '600', color: '#D1FAE5', flex: 1 },
  waves: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  wave: { width: 3, backgroundColor: '#10B981', borderRadius: 2 },
  camMini: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F0FDF4',
    borderWidth: 1.5,
    borderColor: '#A7F3D0',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  camMiniLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  camMiniIcon: {
    width: 34,
    height: 34,
    borderRadius: 9,
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  camMiniText: { fontSize: 13, fontWeight: '700', color: '#065F46' },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(220,38,38,0.08)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(220,38,38,0.2)',
  },
  livePillText: { fontSize: 10, fontWeight: '800', color: '#DC2626', letterSpacing: 0.5 },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingTop: 11,
    paddingBottom: 2,
  },
  toggleText: { fontSize: 12, fontWeight: '700', color: '#64748B' },

  // ── CONFIG CARDS ─────────────────────────────────────────
});
